use serde_json::{Value,json};
use crate::{protocol::fidelity::FidelityRecords,semantic::{task::generation::{ContentPart,GenerationControls,GenerationRequest,Instruction,InstructionAuthority,Item,ItemId,Message,MessageRole,Part,PartId},value::Text}};
#[derive(Clone,Debug,PartialEq)] pub struct DecodedChat{pub semantic:GenerationRequest,pub fidelity:FidelityRecords}
pub fn decode_generation(v:&Value)->Result<DecodedChat,ChatCodecError>{
 let o=v.as_object().ok_or(ChatCodecError::ExpectedObject)?;let ms=o.get("messages").and_then(Value::as_array).ok_or(ChatCodecError::MissingMessages)?;let(mut items,mut iid,mut pid)=(Vec::new(),1u64,1u64);
 for m in ms{let m=m.as_object().ok_or(ChatCodecError::InvalidMessage)?;let role=m.get("role").and_then(Value::as_str).ok_or(ChatCodecError::InvalidMessage)?;let s=m.get("content").and_then(Value::as_str).ok_or(ChatCodecError::InvalidMessage)?;let t=Text::new(s,"message text",1<<20).map_err(|_|ChatCodecError::InvalidMessage)?;let id=ItemId::new(iid);iid+=1;
 let item=match role{"system"=>Item::Instruction(Instruction{authority:InstructionAuthority::System,text:t}),"developer"=>Item::Instruction(Instruction{authority:InstructionAuthority::Developer,text:t}),"user"|"assistant"=>{let p=Part{id:PartId::new(pid),content:ContentPart::Text(t)};pid+=1;Item::Message(Message{role:if role=="user"{MessageRole::User}else{MessageRole::Assistant},parts:vec![p]})},_=>return Err(ChatCodecError::UnsupportedRole)};items.push((id,item));}
 let mut c=GenerationControls{max_output_tokens:o.get("max_completion_tokens").and_then(Value::as_u64),..Default::default()};if let Some(t)=o.get("temperature").and_then(Value::as_f64){c=c.with_temperature(t).map_err(|_|ChatCodecError::InvalidControl)?}
 Ok(DecodedChat{semantic:GenerationRequest::new(items,c).map_err(|_|ChatCodecError::InvalidSemantic)?,fidelity:FidelityRecords::default()})
}
pub fn encode_generation(r:&GenerationRequest)->Value{let mut ms=Vec::new();for(_,i)in r.items(){match i{Item::Instruction(x)=>ms.push(json!({"role":match x.authority{InstructionAuthority::System=>"system",InstructionAuthority::Developer=>"developer"},"content":x.text.as_str()})),Item::ToolCall(_)|Item::ToolResult(_)=>{},Item::Message(m)=>{let s=m.parts.iter().map(|p|match &p.content{ContentPart::Text(t)=>t.as_str(),ContentPart::Resource(_)=>""}).collect::<Vec<_>>().join("");ms.push(json!({"role":match m.role{MessageRole::User=>"user",MessageRole::Assistant=>"assistant"},"content":s}))}}}let mut v=json!({"messages":ms});let o=v.as_object_mut().unwrap();if let Some(x)=r.controls().max_output_tokens{o.insert("max_completion_tokens".into(),json!(x));}if let Some(x)=r.controls().temperature(){o.insert("temperature".into(),json!(x));}v}
#[derive(Clone,Debug,Eq,thiserror::Error,PartialEq)] pub enum ChatCodecError{#[error("expected object")]ExpectedObject,#[error("messages required")]MissingMessages,#[error("invalid message")]InvalidMessage,#[error("unsupported role")]UnsupportedRole,#[error("invalid control")]InvalidControl,#[error("invalid semantics")]InvalidSemantic}
